{{- if and .Values.httpsKeyStore.enable ( not  .Values.httpsKeyStore.jksSecretName ) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "metabase.fullname" . }}-https-jks
  namespace: {{ .Release.Namespace }}
  labels:
    "app.kubernetes.io/name": '{{ template "metabase.name" .}}'
    "helm.sh/chart": "{{ .Chart.Name }}-{{ .Chart.Version }}"
    "app.kubernetes.io/managed-by": "{{ .Release.Service }}"
    "app.kubernetes.io/instance": "{{ .Release.Name }}"
    "app.kubernetes.io/component": "{{ .Values.componentName }}"
type: Opaque
data:
  keystore.jks: |
{{ .Values.httpsKeyStore.jenkinsKeyStoreBase64Encoded | indent 4 }}
  jks-password: {{ .Values.httpsKeyStore.password | b64enc }}
{{- end }}